CREATE TABLE MOVIES
(
Id NUMBER(2),
Title VARCHAR2(20),
Director VARCHAR2(20),
Year NUMBER(4),
Length_minutes NUMBER(3)

);
DROP TABLE MOVIDES;

INSERT INTO MOVIES VALUES(1,'Toy Story','John Lasseter',1995,81);

SELECT M.TITLE,M.DIRECTOR FROM MOVIES M WHERE
LENGTH_MINUTES<100;

SELECT TITLE AS "MOVIE TITLE",DIRECTOR AS "MOVIE DIRECTOR"
FROM MOVIES ;

SELECT TITLE AS "MOVIE TITLE",DIRECTOR AS "MOVIE DIRECTOR"
FROM MOVIES ORDER BY year;
SELECT CONCAT(TITLE,DIRECTOR)AS TILE_DIRECTOR FROM MOVIES;

